"""add suspension fields to users

Revision ID: 736218ddbb2b
Revises: 9e57ba4ccc07
Create Date: 2026-06-18 14:46:49.371307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736218ddbb2b'
down_revision: Union[str, Sequence[str], None] = '9e57ba4ccc07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('users',sa.Column('is_suspended',sa.Boolean(),nullable=False,server_default=sa.false()))

    op.add_column('users',sa.Column('suspension_reason',sa.Text(),nullable=True))

    op.alter_column('users','is_suspended',server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'is_suspended')
    # ### end Alembic commands ###
