"""add otp fields

Revision ID: 9775b762db23
Revises: 8d113e5cb70d
Create Date: 2026-06-11 13:20:24.392104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9775b762db23'
down_revision: Union[str, Sequence[str], None] = '8d113e5cb70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###
