"""replace_age_with_dob

Revision ID: fc38d951457b
Revises: 9775b762db23
Create Date: 2026-06-12 17:06:53.800920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc38d951457b'
down_revision: Union[str, Sequence[str], None] = '9775b762db23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.alter_column('profiles', 'zodiac_sign',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('profiles', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('profiles', 'zodiac_sign',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('profiles', 'date_of_birth')
    # ### end Alembic commands ###
